package com.techstack.drools.validation.agendagroup.step2

import com.techstack.drools.domain.Validation;
import com.techstack.drools.domain.VisaApplication;
import com.techstack.drools.domain.Visa
import java.time.LocalDate

/*
'salience' is a keyword in Drools where we can set
rule execution order.
    Higher order rules will be executed first.
    Lower order rules will be executed last.
    Equal order rules will be exeucted in any order by Rule engine.
*/
rule "Issue visa for valid applications"
	dialect "mvel"
	salience -100
	when
	  $visaApplication: VisaApplication( validation == Validation.PASSED )
	then
	  Visa visa = new Visa( $visaApplication.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insert( visa )
end
