package com.techstack.drools.validation.stateless.step5

import com.techstack.drools.domain.Passport
import com.techstack.drools.domain.Validation
import java.time.LocalDate
import com.techstack.drools.domain.Validation

/*
In this rule, If Validation is UNKNOWN, then mark Passport Validation as PASSED.package
Later we would take decisions based on the other rules configuration.
*/
rule "Valid passport"
  dialect "mvel"
  when
	$passport: Passport( validation == Validation.UNKNOWN )
  then
	System.out.println( $passport + " is without validation info, consider CORRECT for now" );
	$passport.setValidation( Validation.PASSED );
end

rule "Expired passport"
  dialect "mvel"
  when
	$passport: Passport( isExpired() )
  then
	System.out.println( $passport + " is INVALID because it is expired" );
	$passport.setValidation( Validation.FAILED );
end

rule "Full passport"
  dialect "mvel"
  when
	$passport: Passport( unusedVisaPages == 0 )
  then
	System.out.println( $passport + " is INVALID because it has no space for visa" );
	$passport.setValidation( Validation.FAILED );
end
