package com.techstack.drools.validation.group.step3

import com.techstack.drools.domain.InvalidPassport;
import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.InvalidFamilyVisaApplication;
import com.techstack.drools.domain.FamilyVisaApplication;

import java.time.LocalDate;

rule "Invalidate visa applications with invalid passport"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		exists InvalidPassport( $familyVisaApplication.passportNumbers.contains(this.passport.passportNumber) )
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) )
end

rule "Invalidate visa application where everyone is under 16"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		forall (
        $passport : Passport( $familyVisaApplication.passportNumbers.contains(this.passportNumber) ),
                    Passport( this == $passport, this.age < 16)
		)
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as everyone is younger than 16");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) )
end
