package com.techstack.drools.validation.agendagroup.step6
 
import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.Validation;
import com.techstack.drools.domain.VisaApplication;
import java.time.LocalDate;

rule "Switch agenda to visa application validation"
	dialect "mvel"
	when
		not Passport( validation == Validation.UNKNOWN )
	then
		System.out.println( "There are no more passports without validation info" );
		drools.setFocus( "validate-application" );
end

rule "Switch agenda to visa issue"
	dialect "mvel"
	when
		not VisaApplication( validation == Validation.UNKNOWN )
	then
		System.out.println( "There are no more visa applications without validation info" );
		drools.setFocus( "issue-visa" );
end
