package com.techstack.drools.validation.stateful.step2

import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.Validation;
import java.time.LocalDate;

/*
For Validation FAILED cases, we have to set some message
stating that for what reason the rule marked the given data as FAILED
is called "Cause". This is called type inference.

You can set as many as methods inside the modify block
*/
rule "Expired passport"
	dialect "mvel"
	when
		$passport: Passport( isExpired()  )
	then
		System.out.println( $passport + " is INVALID because it is expired" );
		modify($passport) {
		  setValidation( Validation.FAILED ),
		  setCause( "passport is expired" )
		}
end

rule "Full passport"
	dialect "mvel"
	when
		$passport: Passport( unusedVisaPages == 0   )
	then
		System.out.println( $passport + " is INVALID because it has no space for visa" );
		modify($passport) {
		  setValidation( Validation.FAILED ),
		  setCause( "passport has no space for visa" )
		}
end

rule "Valid passport"
	dialect "mvel"
	when
		$passport: Passport( validation == Validation.UNKNOWN )
	then
		System.out.println( $passport + " is without validation info, consider CORRECT for now" );
		modify($passport) {
		  setValidation( Validation.PASSED )
		}
end
