

import com.techstack.drools.domain.InvalidPassport;
import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.InvalidFamilyVisaApplication;
import com.techstack.drools.domain.FamilyVisaApplication;

import java.time.LocalDate;

rule "Invalidate visa applications with invalid passport"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		InvalidPassport( $familyVisaApplication.passportNumbers.contains(this.passport.passportNumber) )
	then
		System.out.println( "Set " + $familyVisaApplication + " invalid as it contains invalid passport");
		insert( new InvalidFamilyVisaApplication($familyVisaApplication) )
end
