package com.techstack.drools.validation.group.step5

import com.techstack.drools.domain.InvalidFamilyVisaApplication;
import com.techstack.drools.domain.FamilyVisaApplication;
import com.techstack.drools.domain.Visa;

import java.time.LocalDate;

rule "Issue visas for valid applications"
	dialect "mvel"
	when
		$familyVisaApplication: FamilyVisaApplication( )
		not ( InvalidFamilyVisaApplication( this.familyVisaApplication == $familyVisaApplication ) )
	then
		for (String passportNumber : $familyVisaApplication.getPassportNumbers()) {
		  System.out.println( "Issue visa for passport number " + passportNumber);
		  insertLogical( new Visa( passportNumber ) )
		}
end
