package com.techstack.drools.validation.logical.step4

import com.techstack.drools.domain.InvalidPassport;
import com.techstack.drools.domain.InvalidVisaApplication;
import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.Visa;
import com.techstack.drools.domain.VisaApplication

rule "Issue visa for valid applications"
	dialect "mvel"
	when
	  $visaApplication: VisaApplication( )
	  $passport: Passport( this.passportNumber == $visaApplication.passportNumber )
	  not InvalidPassport( this.passport == $passport )
	  not InvalidVisaApplication( this.visaApplication == $visaApplication )
	then
	  Visa visa = new Visa( $passport.getPassportNumber() );
	  System.out.println("Issue " + visa);
	  insertLogical( visa )
end
