package com.techstack.drools.validation.logical.step4

import com.techstack.drools.domain.InvalidVisaApplication;
import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.Validation;
import com.techstack.drools.domain.VisaApplication;

rule "Invalidate visa application where passport expires earlier than 6 months after visit end date"
  dialect "mvel"
  when
    $passport: Passport()
    $visaApplication: VisaApplication( passportNumber == $passport.passportNumber,
                       $passport.expiresOn.isBefore(visitEndDate.plusMonths(6)) )
  then
    System.out.println( "Set " + $visaApplication + " invalid as " + $passport + " is not valid 6 months after visit");
    insert( new InvalidVisaApplication($visaApplication) )
end
