package com.techstack.drools.validation.stateless.step6

import java.time.LocalDate
import com.techstack.drools.domain.Passport;
import com.techstack.drools.domain.Validation;

rule "Expired passport"
  dialect "mvel"
  when
	$passport: Passport( isExpired() )
  then
	System.out.println( $passport + " is INVALID because it is expired" );
	$passport.setValidation( Validation.FAILED );
end

rule "Full passport"
  dialect "mvel"
  when
	$passport: Passport( unusedVisaPages == 0 )
  then
	System.out.println( $passport + " is INVALID because it has no space for visa" );
	$passport.setValidation( Validation.FAILED );
end

/*
Here, Rule has moved from First position to Last position. Compare Step5 with Step6,
Lets see what would happen.

Here in Step6 previous two rules are executed and set the Validation status.
However, when Rule processor comes to this rule to execute this, it may not aware
what was changed in the previous rule logic (because of Stateless).
*/
rule "Valid passport"
  dialect "mvel"
  when
	$passport: Passport( validation == Validation.UNKNOWN )
  then
	System.out.println( $passport + " is without validation info, consider CORRECT for now" );
	$passport.setValidation( Validation.PASSED );
end
